config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  # Authentication Related Routes
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'

  resources :members, except: :destroy
  resources :events, except: :destroy
  resources :users, only: :index
  resources :meetings, except: :destroy

  get '/calendar_events/generate_pdf',
    to: 'calendar_events#generate_pdf',
    as: 'calendar_events_generate_pdf'

  resources :calendar_events


  post '/users/bulk_update',
    to: 'users#bulk_update'

  # Reports
  get '/reports/attendance/summary',
    to: 'attendance_report#summary',
    as: 'attendance_summary'

  get '/reports/attendance/all_members', 
    to: 'attendance_report#all_members', 
    as: 'attendance_all_members'
  get '/reports/attendance/generate',
    to: 'attendance_report#generate',
    as: 'attendance_generate'
  get '/reports/attendance/:member_id',
    to: 'attendance_report#generate',
    as: 'attendance_report'
  post '/reports/attendance/generate_pdf',
    to: 'attendance_report#generate_pdf',
    as: 'attendance_generate_pdf'

  get '/reports/attendance/generate',
    to: redirect('/reports/attendance/start'),
    as: 'attandance_generate_get'

  get '/reports/attendance/generate_pdf',
    to: redirect('/reports/attendance/start'),
    as: 'attendance_generate_pdf_get'

  #Meetings
  get '/mettings/by_year/:year',
    to: 'meetings#by_year',
    as: 'meetings_by_year'

  #Events
  get '/events/by_date/:date',
    to: 'events#by_date',
    as: 'events_by_date'
end

app/models/meeting.rb
class Meeting < Airrecord::Table
  MEETING_TYPE_MAP = {
    'GM' => 'General Meeting',
    'Board' => 'Board'
  }

  MEETING_SET_TYPE_MAP = MEETING_TYPE_MAP.invert

  self.base_key = ENV['AIRTABLE_APP_KEY']
  self.table_name = 'Meetings'

  map_field :type, 'Meeting Type'
  map_date_field :date, 'Date'
  map_field :attendees_raw, 'Attendees'

  has_many :attendees,
    class: 'Member',
    column: 'Attendees'

  validates :type, inclusion: MEETING_TYPE_MAP.keys
  validates :attendees_raw, presence: {message: 'must select at least one'}

  def last_12_months?
    self['If Last 12 Months'] == 1
  end

  def verbose_type
    MEETING_TYPE_MAP[type]
  end

  def verbose_type=(new_val)
    self.type = MEETING_SET_TYPE_MAP[new_val]
  end

  def allowed_verbose_types
    MEETING_SET_TYPE_MAP.keys
  end

  def self.for_year(year)
    time = Time.zone.local(year.to_i)
    start_date = (time - 1.day).strftime('%Y-%d-%m')
    end_date = (time.end_of_year + 1.day).strftime('%Y-%d-%m')
    self.all(
      filter: "AND({Date} > '#{start_date}', {Date} < '#{end_date}')",
      sort: { "Date" => "asc" }
    )
  end

  def self.within_12_months
    all(filter: "{If Last 12 Months} = 1")
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  include MeetingsHelper
  include SharedFormHelper
  before_action :authenticate, only: [:index, :show]
  before_action :authorize_secretary, only: [:edit, :update, :new, :create]
  before_action :authenticate_api, only: [:by_date_range]

  def by_year
    render json: meetings_by_year(params[:year])
  end

  def index
  end

  def show
    @meeting = Meeting.find(params[:id])
    @can_edit = can_edit?
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    meeting_params = params.permit(meeting: {}).to_h.fetch(:meeting)
    clean_blanks_from_form(meeting_params)
    parse_date_parts(meeting_params, :date)

    @meeting = Meeting.find(params[:id])
    @meeting.assign_attributes(meeting_params)

    if @meeting.changed?
      if @meeting.valid?
        @meeting.save
        flash[:success] = "Saved meeting changes!"
      else
        flash[:error] = @meeting.errors.messages.map do |field_name, message|
          "#{field_name.to_s.titleize} #{message.join(",")}"
        end
      end
    else
      flash[:info] = "No changes detected."
    end

    redirect_to action: :show, id: @meeting.id
  end

  def new
    @meeting = Meeting.empty
    @meeting.date = Time.zone.today
  end

  def create
    meeting_params = params.permit(meeting: {}).to_h.fetch(:meeting)
    clean_blanks_from_form(meeting_params)
    parse_date_parts(meeting_params, :date)
    @meeting = Meeting.new_assign_attributes(meeting_params)

    if @meeting.valid?
      @meeting.save
      fields = @meeting.fields.clone
      fields['id'] = @meeting.id
      MeetingsMailer.with(meeting: fields).new_meeting_email.deliver_later
      flash[:success] = "Meeting created!"
      redirect_to action: :show, id: @meeting.id
    else
      flash[:error] = @meeting.errors.messages.map do |field_name, message|
        "#{field_name.to_s.titleize} #{message.join(",")}"
      end
      render 'new'
    end
  end

  private

  def meetings_by_year(year)
    Meeting.for_year(year).map do |m|
      {
        type: m.type,
        date: date_display(m.date),
        href: meeting_path(m.id)
      }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def member_records
    Member.all(sort: { 'Pseudonym' => 'asc' })
  end

  def can_edit?
    is_secretary? || is_admin?
  end
end

app/views/meetings/_meetings_form.html.haml
.container
  = bootstrap_form_with model: @meeting,
    url: url,
    method: local_assigns.fetch(:method, :post),
    layout: :horizontal,
    local: true do |f|

    = f.date_select :date
    = f.select :verbose_type, @meeting.allowed_verbose_types, label: 'Type of Meeting'
    = collection_check_boxes_columns f, :attendees_raw,
      member_records, :id, :pseudonym, label_text: 'Attendees'
    = f.primary submit_text unless submit_text.nil?

app/views/meetings/edit.html.haml
%h1 Edit Meeting
= render partial: 'meetings_form', locals: { submit_text: 'Save Changes',
  url: {controller: 'meetings', action: 'update', id: @meeting.id},
  method: :put}

app/views/meetings/index.html.haml
- title 'Meetings'
%h2 Manage Meeting Attendance
.d-flex.justify-content-end
  = link_to 'Create New Meeting', new_meeting_path,
    class: 'btn btn-primary'
- content_for(:desc) do
  %p Please select the link below for the meeting you wish to view.
= render 'shared/year_search_form'
:javascript
  SfspiUi.setupYearSearchForm(
    Routes.meetings_by_year_path,
    SfspiUi.meetingsTranslator
  )

app/views/meetings/new.html.haml
%h1 Create Meeting
= render partial: 'meetings_form', locals: { submit_text: 'Save Changes',
  url: {controller: 'meetings', action: 'create', id: @meeting.id}}

app/views/meetings/show.html.haml
%h1 Meeting Information
- if @can_edit
  .d-flex.justify-content-end
    = link_to 'Edit this Meeting', edit_meeting_path(@meeting.id)
.container
  = bootstrap_form_with model: @meeting,
    url: '#',
    layout: :horizontal do |f|

    = f.static_control :date
    = f.static_control :verbose_type, label: 'Type of Meeting'
    = collection_check_boxes_columns f, :attendees_raw,
      member_records, :id, :pseudonym, label_text: 'Attendees', disabled: true