config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  # Authentication Related Routes
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'

  resources :members, except: :destroy
  resources :events, except: :destroy
  resources :users, only: :index
  resources :meetings, except: :destroy

  get '/calendar_events/generate_pdf',
    to: 'calendar_events#generate_pdf',
    as: 'calendar_events_generate_pdf'

  resources :calendar_events


  post '/users/bulk_update',
    to: 'users#bulk_update'

  # Reports
  get '/reports/attendance/summary',
    to: 'attendance_report#summary',
    as: 'attendance_summary'

  get '/reports/attendance/all_members', 
    to: 'attendance_report#all_members', 
    as: 'attendance_all_members'
  get '/reports/attendance/generate',
    to: 'attendance_report#generate',
    as: 'attendance_generate'
  get '/reports/attendance/:member_id',
    to: 'attendance_report#generate',
    as: 'attendance_report'
  post '/reports/attendance/generate_pdf',
    to: 'attendance_report#generate_pdf',
    as: 'attendance_generate_pdf'

  get '/reports/attendance/generate',
    to: redirect('/reports/attendance/start'),
    as: 'attandance_generate_get'

  get '/reports/attendance/generate_pdf',
    to: redirect('/reports/attendance/start'),
    as: 'attendance_generate_pdf_get'

  #Meetings
  get '/mettings/by_year/:year',
    to: 'meetings#by_year',
    as: 'meetings_by_year'

  #Events
  get '/events/by_date/:date',
    to: 'events#by_date',
    as: 'events_by_date'
end

app/models/calendar_event.rb
class CalendarEvent < Airrecord::Table
  self.base_key = ENV['AIRTABLE_APP_KEY']
  self.table_name = 'Calendar Events'

  EVENT_TYPES = ['Event', 'Holiday']

  has_many :point_members,
    class: 'Member',
    column: 'Point Members'

  map_field :point_members_raw, 'Point Members'

  map_field :name, 'Name'
  map_field :location, 'Location'
  map_datetime_field :start_time, 'Start Time'
  map_datetime_field :end_time, 'End Time'
  map_checkbox_field :approved, 'Approved'
  map_checkbox_field :start_time_tbd, 'Start Time TBD'
  map_checkbox_field :end_time_tbd, 'End Time TBD'
  map_checkbox_field :all_day, 'All Day'
  map_field :type, 'Type'

  validates_presence_of :location, if: :is_event? 

  validates_presence_of :name, :start_time, :end_time
  
  validates_presence_of :point_members_raw,
    message: 'must select at least one', if: :is_event?

  validate :dates_make_sense?

  validates :type, inclusion: { in: EVENT_TYPES }

  def start_time_display
    if all_day || start_time_tbd
      date_display start_time 
    else
      time_display start_time 
    end
  end

  def end_time_display
    if all_day || end_time_tbd
      date_display end_time 
    else
      time_display end_time 
    end
  end

  def is_event?
    type == 'Event'
  end

  def is_holiday?
    type == 'Holiday'
  end

  def self.for_month(date)
    start_date = date.beginning_of_month - 6.days
    end_date = date.end_of_month + 6.days
    self.all(
      filter: 
        "AND(" \
        "IS_BEFORE({Start Time},DATETIME_PARSE('#{end_date.iso8601}')),"\
        "IS_AFTER({Start Time},DATETIME_PARSE('#{start_date.iso8601}'))" \
        ")"
    )
  end

  def self.for_year(year)
    start_date = Time.zone.local(year.to_i, 1, 1)
    end_date   = Time.zone.local(year.to_i, 12, 31)
    self.all(
      filter:
      "AND(" \
      "IS_BEFORE({Start Time}, DATETIME_PARSE('#{end_date.iso8601}')),"\
      "IS_AFTER({Start Time}, DATETIME_PARSE('#{start_date.iso8601}'))"\
      ")"
    )
  end

  # Arguments must respond to #iso8601
  def self.for_range(start_date, end_date)
    self.all(
      filter:
      "AND(" \
      "IS_BEFORE({Start Time}, DATETIME_PARSE('#{end_date.iso8601}')),"\
      "IS_AFTER({Start Time}, DATETIME_PARSE('#{start_date.iso8601}'))"\
      ")"
    )
  end

  def self.allowed_event_types
    EVENT_TYPES
  end

  private

  def dates_make_sense?
    return if [start_time.blank?, end_time.blank?].any?
    if start_time > end_time
      errors.add(:start_time, 'must be before the end time')
    end
  end

  def time_display(time)
    time.strftime('%B %-d, %Y %-I:%M %p %Z') unless time.nil?
  end

  def date_display(time)
    time.strftime('%B %-d, %Y') unless time.nil?
  end
end

app/controllers/calendar_events_controller.rb
class CalendarEventsController < ApplicationController
  include SharedFormHelper
  include CalendarEventsHelper
  before_action :set_calendar_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate
  before_action :authorize_calendar_admin, only: [:destroy]

  # GET /calendar_events
  # GET /calendar_events.json
  def index
    go_to_form = params.permit(go_to: {}).to_h.fetch(:go_to, nil)
    if params[:start_date]
      start_date = params[:start_date] = params[:start_date].to_date
    elsif go_to_form
      parse_date_parts(go_to_form, :date)
      params[:start_date] = start_date = go_to_form[:date]
    else
      params[:start_date] = start_date = Time.zone.today
    end

    @calendar_events = CalendarEvent.for_month(start_date) + birthday_events
  end

  # GET /calendar_events/1
  # GET /calendar_events/1.json
  def show
  end

  # GET /calendar_events/new
  def new
    @calendar_event = CalendarEvent.empty
  end

  # GET /calendar_events/1/edit
  def edit
  end

  # POST /calendar_events
  # POST /calendar_events.json
  def create
    @calendar_event = CalendarEvent.new_assign_attributes(calendar_event_params)

    if @calendar_event.valid?
      @calendar_event.save if @calendar_event.changed?
      calendar_fields = @calendar_event.fields.clone
      calendar_fields['id'] = @calendar_event.id
      if @calendar_event.type == 'Event'
        CalendarEventsMailer.with(calendar_event: calendar_fields)
          .new_calendar_event_email
          .deliver_later
      end
      flash[:info] = 'Calendar event sucessfully created.'
      redirect_to action: :show, id: @calendar_event.id 
    else
      render :new 
    end
  end

  # PATCH/PUT /calendar_events/1
  # PATCH/PUT /calendar_events/1.json
  def update
    @calendar_event.assign_attributes(calendar_event_params)
    if @calendar_event.changed? && @calendar_event.valid?
      @calendar_event.save
      flash[:info] = 'Calendar event was successfully updated.'
      redirect_to action: :show, id: @calendar_event.id 
    else
      render :edit
    end
  end

  # DELETE /calendar_events/1
  # DELETE /calendar_events/1.json
  def destroy
    @calendar_event.destroy
    respond_to do |format|
      flash[:info] = 'Calendar event was successfully removed.'
      format.html { redirect_to calendar_events_url}
      format.json { head :no_content }
    end
  end

  def generate_pdf
    @start_date = Time.zone.today.beginning_of_month
    @year = @start_date.year
    @end_date = (@start_date + 11.months).end_of_month
    @calendar_events = CalendarEvent.for_range(@start_date, @end_date) + birthday_events
    @months = months_in_events(@calendar_events)
    if params[:html] == 'true'
      render 'calendar_events/pdf_calendar', layout: 'pdf'
    else
      render pdf: "sfspi_calendar.pdf",
         disposition: 'inline',
         template: 'calendar_events/pdf_calendar',
         layout: 'pdf',
         dpi: '200',
         page_size: 'letter',
         orientation: 'Portrait',
         disable_internal_links: true,
         disable_external_links: true
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_calendar_event
    @calendar_event = CalendarEvent.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def calendar_event_params
    the_params = params.permit(calendar_event: {})
      .to_h
      .fetch(:calendar_event)
    clean_blanks_from_form(the_params)

    parse_date_parts(the_params, :start_time)
    parse_date_parts(the_params, :end_time)
    the_params
  end

  def birthday_events
    Member.active.map do |m|
      next if m.birthday.nil?
      c = CalendarEvent.empty
      date = Time.zone.local(
        year_for(m.birthday.month),
        m.birthday.month,
        m.birthday.day
      )
      c.start_time = date
      c.end_time = date
      c.all_day = true
      c.type = 'Birthday'
      c.name = "#{m.pseudonym} Birthday"
      c.approved = true
      c
    end.compact
  end

  def months_in_events(events)
    months = Set.new
    events.each_with_object(months) do |event, months|
      months.add(event.start_time.month)
      months.add(event.end_time.month)
    end
    months.sort.partition{ |m| m >= @start_date.month }.flatten
  end
end

app/helpers/calendar_events_helper.rb
module CalendarEventsHelper
  def start_to_end_string(calendar_event)
    return '' if calendar_event.all_day
    return 'TBD' if calendar_event.start_time_tbd && calendar_event.end_time_tbd

    if calendar_event.start_time_tbd
      start_time = 'TBD'
    else
      start_time = calendar_event.start_time.strftime('%l:%M %p')
    end

    if calendar_event.end_time_tbd
      end_time = 'TBD'
    else
      end_time   = calendar_event.end_time.strftime('%l:%M %p')
    end

    "#{start_time} to #{end_time}"
  end

  def active_member_records
    @active_member_records ||= Member.active
  end

  def all_day_first(events)
    all_day_events, remaining_events = events.partition { |e| e.all_day }
    all_day_events + remaining_events
  end

  def event_additional_classes(event)
    classes = []
    classes << 'unapproved-event' if !event.approved
    classes << 'holiday-event' if event.type == 'Holiday'
    classes << 'normal-event' if event.type == 'Event'
    classes << 'birthday-event' if event.type == 'Birthday'
    classes
  end

  def year_for(month)
    reference = Time.zone.today
    if month >= reference.month
      return reference.year
    else
      return reference.year + 1
    end
  end

  def pdf_calendar_header(start_date, end_date)
    "SFSPI Calendar for " \
      "#{@start_date.strftime('%B %Y')} - #{@end_date.strftime('%B %Y')}"
  end
end

app/views/calendar_events/_form.html.haml
.container
  = bootstrap_form_with model: @calendar_event,
    url: url,
    method: local_assigns.fetch(:method, :post),
    layout: :horizontal,
    id: 'calendar_event_form',
    local: true do |f|
    = f.text_field :name, label: 'Event Name', autocomplete: 'none'
    = f.collection_select :type, CalendarEvent.allowed_event_types, 
      :to_s, :to_s 
    = f.text_field :location, label: 'Location'
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :all_day, label: 'All Day'
    = f.datetime_select :start_time, label: 'Start Time', 
      datetime_separator: '&nbsp&nbsp', include_blank: true, default: nil,
      ampm: true, minute_step: 15, 
      time_separator: tag.span(':', id: 'start_timesep')
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :start_time_tbd, label: 'Start Time TBD'
    = f.datetime_select :end_time, label: 'End Time',
      datetime_separator: '&nbsp&nbsp', include_blank: true, default: nil,
      ampm: true, minute_step: 15,
      time_separator: tag.span(':', id: 'end_timesep')
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :end_time_tbd, label: 'End Time TBD'
    = collection_check_boxes_columns f, :point_members_raw,
      active_member_records, :id, :pseudonym, label_text: 'Point Members'
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :approved, label: 'Approved by Connections'
    = f.primary submit_text unless submit_text.nil?
:javascript
  SfspiUi.setupCalendarEventTimeToggles()

app/views/calendar_events/edit.html.haml
%h1 Editing Calendar Event

.d-flex.justify-content-end.my-2
  = link_to 'Show', calendar_event_path(@calendar_event.id), 
    class: 'btn btn-primary mx-2'
  = link_to 'Delete', calendar_event_path(@calendar_event.id),
    data: { confirm: 'Are you sure you want to delete this event?' },
    method: :delete, class: 'btn btn-danger mx-2'
  = link_to 'Back', calendar_events_path, class: 'btn btn-primary mx-2'

= render partial: 'form', locals: { submit_text: 'Update Event',
  url: {controller: 'calendar_events', action: 'update', id: @calendar_event.id},
  method: :put}

app/views/calendar_events/index.html.haml
%h1 Calendar
.d-flex.justify-content-end
  = link_to 'Print Next 12 Months', calendar_events_generate_pdf_path,
    class: 'btn btn-primary mx-2'
  = link_to 'Create New Calendar Event', new_calendar_event_path,
    class: 'btn btn-primary mx-2'

.d-flex.flex-row.my-3
  .p-2.event.holiday-event.align-self-center
    Holidays
  .p-2.event.birthday-event.align-self-center
    Birthdays
  .p-2.event.normal-event.align-self-center
    Sister Event
  .pl-2.py-2.align-self-center
    %img{src: asset_pack_path('src/scss/warning.svg')}
  .pr-2.py-2.mr-auto.align-self-center
    Connections needs to approve
  = bootstrap_form_with scope: :go_to, layout: :inline,
    method: :get, url: calendar_events_path, local: true do |f|
    .p-2
      = f.date_select :date, discard_day: true, use_short_month: true,
        hide_label: true, selected: params[:start_date]
    .p-2
      = f.primary 'Go'

%p Click event name to view details.

=month_calendar events: @calendar_events do |date, events|
  .date=date.day
  -all_day_first(events).each do |e|
    .event{class: event_additional_classes(e)}
      - if e.type == 'Birthday'
        .event-desc=e.name
      - else
        .event-desc=link_to e.name, calendar_event_path(e.id)
      .event-time=start_to_end_string e

app/views/calendar_events/new.html.haml
%h1 New Calendar Event

= render partial: 'form', locals: { submit_text: 'Submit Event', 
  url: {controller: 'calendar_events', action: 'create'}}

app/views/calendar_events/pdf_calendar.html.haml
- title pdf_calendar_header(@start_date, @end_date)
%h1= pdf_calendar_header(@start_date, @end_date)
- @months.each do |month|
  = month_calendar events: @calendar_events,
    start_date: Time.zone.local(year_for(month), month, 1).to_date,
    partial: 'simple_calendar/print_month_calendar' do |date, events|
    .date=date.day
    - if date.month == month
      - all_day_first(events).each do |e|
        .event{class: event_additional_classes(e)}
          .event-desc=e.name
          .event-time=start_to_end_string e
        - content_for(:event_details) do
          %h3= e.name
          %table.table.table-striped#event-details
            %tr
              %th{scope: 'row'} Type
              %td= e.type + (e.all_day && e.type == 'Event' ? ' (All Day)' : '')
            - if e.type == 'Event' && !e.all_day
              %tr
                %th{scope: 'row'} Time of Event
                %td= "#{e.start_time_display} to #{e.end_time_display}"
            - else
              %tr
                %th{scope: 'row'} Date of Event
                %td= "#{e.start_time_display}"
            - if e.type == 'Event'
              %tr
                %th{scope: 'row'} Point Members
                %td= e.point_members.map(&:pseudonym).join(', ')
          %hr
  .page-break
  %h2= "#{t('date.month_names')[month]} Event Details"
  = yield(:event_details) if content_for?(:event_details)
  - content_for(:event_details, flush: true) do
    = ''
  - if month != @months.last
    .page-break

app/views/calendar_events/show.html.haml
- title "Event - #{@calendar_event.name}"
%h1= "Calendar Event: #{@calendar_event.name}"
.d-flex.justify-content-end.my-2
  = link_to 'Edit', edit_calendar_event_path(@calendar_event.id), 
    class: 'btn btn-primary mx-2'
  = link_to 'Delete', calendar_event_path(@calendar_event.id),
    data: { confirm: 'Are you sure you want to delete this event?' },
    method: :delete, class: 'btn btn-danger mx-2'
  = link_to 'Back', calendar_events_path, class: 'btn btn-primary mx-2'
.container
  = bootstrap_form_with(model: @calendar_event,
    url: "#", layout: :horizontal) do |f|
    = f.static_control :type
    = f.static_control :location
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :all_day, label: 'All Day', disabled: true
    = f.static_control label: 'Start Time',
      value: @calendar_event.start_time_display
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :start_time_tbd, label: 'Start Time TBD', disabled: true
    = f.static_control label: 'End Time',
      value: @calendar_event.end_time_display
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :end_time_tbd, label: 'End Time TBD', disabled: true
    = collection_check_boxes_columns f, :point_members_raw,
      active_member_records, :id, :pseudonym, label_text: 'Point Members',
      disabled: true
    .form-group.row
      .col-sm-2
      .col-sm-10
        = f.check_box :approved, label: 'Approved by Connections', disabled: true