config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  # Authentication Related Routes
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#auth_failure'

  resources :members, except: :destroy
  resources :events, except: :destroy
  resources :users, only: :index
  resources :meetings, except: :destroy

  get '/calendar_events/generate_pdf',
    to: 'calendar_events#generate_pdf',
    as: 'calendar_events_generate_pdf'

  resources :calendar_events


  post '/users/bulk_update',
    to: 'users#bulk_update'

  # Reports
  get '/reports/attendance/summary',
    to: 'attendance_report#summary',
    as: 'attendance_summary'

  get '/reports/attendance/all_members', 
    to: 'attendance_report#all_members', 
    as: 'attendance_all_members'
  get '/reports/attendance/generate',
    to: 'attendance_report#generate',
    as: 'attendance_generate'
  get '/reports/attendance/:member_id',
    to: 'attendance_report#generate',
    as: 'attendance_report'
  post '/reports/attendance/generate_pdf',
    to: 'attendance_report#generate_pdf',
    as: 'attendance_generate_pdf'

  get '/reports/attendance/generate',
    to: redirect('/reports/attendance/start'),
    as: 'attandance_generate_get'

  get '/reports/attendance/generate_pdf',
    to: redirect('/reports/attendance/start'),
    as: 'attendance_generate_pdf_get'

  #Meetings
  get '/mettings/by_year/:year',
    to: 'meetings#by_year',
    as: 'meetings_by_year'

  #Events
  get '/events/by_date/:date',
    to: 'events#by_date',
    as: 'events_by_date'
end

app/views/layouts/_favicons.html.haml
%link{href: asset_pack_path("favicons/apple-touch-icon-57x57.png"), 
  rel: "apple-touch-icon-precomposed", sizes: "57x57"}
%link{href: asset_pack_path("favicons/apple-touch-icon-114x114.png"),
  rel: "apple-touch-icon-precomposed", sizes: "114x114"}
%link{href: asset_pack_path("favicons/apple-touch-icon-72x72.png"),
  rel: "apple-touch-icon-precomposed", sizes: "72x72"}
%link{href: asset_pack_path("favicons/apple-touch-icon-144x144.png"),
  rel: "apple-touch-icon-precomposed", sizes: "144x144"}
%link{href: asset_pack_path("favicons/apple-touch-icon-60x60.png"),
  rel: "apple-touch-icon-precomposed", sizes: "60x60"}
%link{href: asset_pack_path("favicons/apple-touch-icon-120x120.png"),
  rel: "apple-touch-icon-precomposed", sizes: "120x120"}
%link{href: asset_pack_path("favicons/apple-touch-icon-76x76.png"),
  rel: "apple-touch-icon-precomposed", sizes: "76x76"}
%link{href: asset_pack_path("favicons/apple-touch-icon-152x152.png"),
  rel: "apple-touch-icon-precomposed", sizes: "152x152"}
%link{href: asset_pack_path("favicons/favicon-196x196.png"),
  rel: "icon", sizes: "196x196", :type => "image/png"}
%link{href: asset_pack_path("favicons/favicon-96x96.png"),
  rel: "icon", sizes: "96x96", :type => "image/png"}
%link{href: asset_pack_path("favicons/favicon-32x32.png"),
  rel: "icon", sizes: "32x32", :type => "image/png"}
%link{href: asset_pack_path("favicons/favicon-16x16.png"),
  rel: "icon", sizes: "16x16", :type => "image/png"}
%link{href: asset_pack_path("favicons/favicon-128.png"),
  rel: "icon", sizes: "128x128", :type => "image/png"}
%meta{content: "#FD7E17", name: "msapplication-TileColor"}
%meta{content: asset_pack_path("favicons/mstile-144x144.png"),
  name: "msapplication-TileImage"}
%meta{content: asset_pack_path("favicons/mstile-70x70.png"),
  name: "msapplication-square70x70logo"}
%meta{content: asset_pack_path("favicons/mstile-150x150.png"),
  name: "msapplication-square150x150logo"}
%meta{content: asset_pack_path("favicons/mstile-310x150.png"),
  name: "msapplication-wide310x150logo"}
%meta{content: asset_pack_path("favicons/mstile-310x310.png"),
  name: "msapplication-square310x310logo"}

- if Rails.env == 'staging'
  %meta{content: 'SFSPI Intranet (Staging)', name: 'application-name'}
- else
  %meta{content: "SFSPI Management System", name: "application-name"}

app/views/layouts/_nav_dropdown.html.haml
%div{:class => nav_item_class}
  %a.nav-link.dropdown-toggle{"aria-expanded" => "false", 
    "aria-haspopup" => "true", "data-toggle" => "dropdown", 
    :href => "#", :id => id, :role => "button"}= name
  .dropdown-menu{"aria-labeledby" => id}
    - links.each do |link|
      = link_to link[:name], link[:path], class: 'dropdown-item',
        data: { turbolinks: !link[:disable_turbo] }, target: link[:target]

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", 
      "http-equiv" => "Content-Type"}
    %title="SFSPI Portal: #{content_for?(:title) ? yield(:title) : 'Home'}"
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", 
      :name => "viewport"}
    = render partial: 'layouts/favicons'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 
      'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.light.bg-light
      %a.navbar-brand{:href => "/"}
        = img_src_set prefix: 'images/logo', ext: 'png',
          default_size: '20w', class: 'img-fluid',
          srcset: [ {size: '20w', max_wdith: '576px', image_size: '20px'},
            {size: '80w', min_width: '992px', image_size: '60px'}, 
            {size: '40w', min_width: '577px', image_size: '40px'} ]
        SFSPI Portal
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", 
        "aria-expanded" => "false", 
        "aria-label" => "Toggle navigation", 
        "data-target" => "#navbarSupportedContent", 
        "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        - if user_signed_in?
          %ul.navbar-nav.mr-auto
            - if current_user.record_link
              = nav_link_to "Calendar", calendar_events_path, :inclusive
              = nav_link_to "Point Nun Reports", events_path, :inclusive
              = nav_link_to "Meeting", meetings_path, :inclusive
              = nav_link_to "Members", members_path, :inclusive
              = dropdown_nav 'Attendance Reports', 'attendanceDropdown',
                /^\/reports\/attendance/, attendance_link_list 
            - if is_admin?
              = dropdown_nav 'Administration', 'adminDropdown', /^\/admin/, 
                [ { name: 'Manage User Roles and Record Links', 
                path: users_path } ]
            - if session[:auth_provider] == 'microsoft_v2_auth'
              = dropdown_nav 'O365', 'o365Dropdown', nil, o365_link_list
            - else
              = dropdown_nav 'GSuite', 'gsuiteDropdown', nil,
                gsuite_link_list
          .navbar-nav
            = dropdown_nav current_user.display_name, 'profileDropdown', 
              /^\/me/, user_dropdown_links
        - else
          .navbar-nav.mr-auto
          .navbar-nav
            - if ENV['ENABLE_GOOGLE_OAUTH'] == 'true'
              %a.btn.btn-primary.mx-1{:href => "/auth/google_oauth2",
                :role => "button"}
                Login with Google
            - if ENV['ENABLE_O365_OAUTH'] == 'true'
              %a.btn.btn-primary.mx-2{:href => "/auth/microsoft_v2_auth", 
                :role => "button"}
                Login with Office365
    - flash.each do |key, value|
      %div{:class => "container #{flash_class(key)}"}
        - if value.is_a? Array
          %ul
            - value.each do |message|
              %li= message
        - else
          = value
    .container.main-container.pt-2
      - if user_signed_in? && current_user.record_link.nil?
        .text-white.bg-danger 
          Please contact the Secretary to finish setting up your user account
      = yield

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    = inline_remote_stylesheet 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'
    = inline_remote_stylesheet 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css'
    :css
      table {
        page-break-inside:auto;
        width: 100%;
      }
      tr  { 
        page-break-inside:avoid; 
        page-break-after:auto;
      }
      thead {
        display:table-header-group
      }
      tfoot { 
        display:table-footer-group
      }
      a {
        color: inherit;
      }
      /* declare a 7 column grid on the table */
      #calendar {
        width: 100%;
        table-layout: fixed;
      }

      #calendar tr, #calendar tbody, #calendar thead {
        grid-column: 1 / -1;
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        width: 100%;
      }

      caption {
        text-align: center;
        grid-column: 1 / -1;
        font-size: 130%;
        font-weight: bold;
        padding: 10px 0;
      }

      #calendar td, #calendar th {
        padding: 5px;
        box-sizing:border-box;
        border: 1px solid #ccc;
      }

      #calendar .weekdays {
      }

      #calendar .weekdays th {
        text-align: center;
        text-transform: uppercase;
        line-height: 20px;
        border: none !important;
        padding: 10px 6px;
        font-size: 13px;
      }

      #calendar td {
        height: 180px;
        display: flex;
        flex-direction: column;
      }

      #calendar .days li:hover {
        background: #d3d3d3;
      }

      #calendar .date {
        text-align: center;
        margin-bottom: 5px;
        padding: 4px;
        background: #333;
        color: #fff;
        width: 30px;
        border-radius: 50%;
        flex: 0 0 auto;
        align-self: flex-end;
      }

      #calendar .event {
        flex: 0 0 auto;
        font-size: 13px;
        border-radius: 4px;
        padding: 5px;
        margin-bottom: 5px;
        line-height: 14px;
        border: 1px solid gray('500');
        text-decoration: none;
      }

      #calendar .event-desc {
        margin: 3px 0 7px 0;
        text-decoration: none;	
      }

      #calendar .prev-month, #calendar .next-month {
        background-color: #ced4da;
        color: #666;
      }

      #calendar .prev-month .event {
        display: none;
      }

      .event.holiday-event {
        background-color: #fdf1f2;
      }

      .event.normal-event {
        //background: rgba(180, 220, 220, 0.5);
        background-color: #daeeed;
      }

      .event.birthday-event {
        background-color: #d4e6f7;
      }

      #calendar .event.unapproved-event {
        background-image: url('warning.svg');
        background-repeat: no-repeat;
        background-position: right 3px top 3px;
        background-attachment: local;
      }

      #event-details {
        table-layout: fixed;
      }

      #event-details th {
        width: 30%;
      }

      .page-break { 
        display: block;
        clear: both;
        page-break-after: always;
      }
    = inline_remote_js 'https://code.jquery.com/jquery-3.3.1.slim.min.js'
    = inline_remote_js 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'
    = inline_remote_js 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'
    :javascript
      $(document).ready(function() {
        $('a').contents().unwrap()
      })
  %body
    #content
      = yield